# Generated by Django 4.1 on 2022-08-21 22:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("Y", "Year"),
                            ("Q", "Quarter"),
                            ("M", "Month"),
                            ("W", "Week"),
                        ],
                        default="",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(null=True)),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Q1"),
                            (2, "Q2"),
                            (3, "Q3"),
                            (4, "Q4"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "week",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                ("calculated", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GoalModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("W", "WIP"),
                            ("D", "Done"),
                            ("C", "Cancelled"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                ("started", models.DateTimeField(null=True)),
                ("finished", models.DateTimeField(null=True)),
                (
                    "due_time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goals.timemodel",
                    ),
                ),
                (
                    "parent_goal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="goals.goalmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
